# https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  - package-ecosystem: "npm"
    labels:
      - "npm dependencies"
    directory: "/"
    open-pull-requests-limit: 0 # Disable version updates
    schedule:
      interval: "daily"
      time: "13:55"
      timezone: "Asia/Tbilisi"  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

  - package-ecosystem: "gradle"
    labels:
      - "gradle dependencies"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
      time: "13:55"
      timezone: "Asia/Tbilisi"
